### ISSUE TITLE
Missing migration on pip

### ISSUE THREAD

**Issue by xkill** [mathiasertl/django-ca#33] opened 2017-11-17 14:47 UTC
If you install django-ca using pip, and then use it on a django project, when you call makemigrations a new migration on the django-ca python library is created (if root, otherwise an error appears)

this is the migration:
```python
# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_ca', '0006_auto_20170505_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='django_ca.CertificateAuthority'),
        ),
    ]
```

**Comment by mathiasertl** [comment] 2017-12-14 21:26
The issue is fixed in django-ca 1.7.0, which I just released.

**Closed by mathiasertl** 2017-12-14 21:26 UTC
